bug: Missing a benchmark when tuning triggers an error
```julia
Missing Reference Benchmark: Error During Test at /Users/alexwadell/.julia/dev/PkgJogger/test/tune.jl:78
  Got exception outside of a @test
  MethodError: no method matching tune!(::BenchmarkTools.Benchmark)
  Closest candidates are:
    tune!(::BenchmarkTools.Benchmark, ::Any; kwargs...) at ~/.julia/dev/PkgJogger/src/utils.jl:192
    tune!(::BenchmarkGroup; kwargs...) at ~/.julia/dev/PkgJogger/src/utils.jl:186
    tune!(::BenchmarkGroup, ::BenchmarkGroup; pad, kwargs...) at ~/.julia/dev/PkgJogger/src/utils.jl:171
    ...
  Stacktrace:
    [1] tune!(group::BenchmarkGroup, ref::BenchmarkGroup; pad::String, kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
      @ PkgJogger ~/.julia/dev/PkgJogger/src/utils.jl:178
    [2] tune!(group::BenchmarkGroup, ref::BenchmarkGroup)
      @ PkgJogger ~/.julia/dev/PkgJogger/src/utils.jl:172
    [3] tune!(group::BenchmarkGroup, ref::BenchmarkGroup; pad::String, kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
      @ PkgJogger ~/.julia/dev/PkgJogger/src/utils.jl:175
    [4] tune!(group::BenchmarkGroup, ref::BenchmarkGroup)
      @ PkgJogger ~/.julia/dev/PkgJogger/src/utils.jl:172
```